# Generated by Django 4.2.6 on 2023-10-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_projects_options_rename_title_projects_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='language',
            field=models.CharField(default='', max_length=20, verbose_name='Язык программирования'),
        ),
    ]
