# Generated by Django 4.2.6 on 2023-10-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_alter_projects_descript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='language',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='Язык программирования'),
        ),
    ]
