# Generated by Django 4.2.6 on 2023-10-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_projects_repo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='url',
            field=models.CharField(default='', max_length=250, null=True, verbose_name='Ссылка'),
        ),
    ]
