# Generated by Django 4.2.6 on 2023-11-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_projects_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='date',
            field=models.DateField(verbose_name='Дата создания'),
        ),
    ]
